# Generated by Django 4.2.30 on 2026-06-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[("C", "Customer"), ("S", "Staff")], default="C", max_length=1
            ),
        ),
    ]
