# Generated by Django 4.2.30 on 2026-06-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Movie", "0003_alter_movie_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("adress", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ShopMovieAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_stock", models.IntegerField(default=0)),
                ("rental_stock", models.IntegerField(default=0)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Movie.movie"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Shop.shop"
                    ),
                ),
            ],
            options={
                "unique_together": {("shop", "movie")},
            },
        ),
    ]
