# Generated by Django 4.2.30 on 2026-07-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopmovieavailability",
            name="purchase_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="shopmovieavailability",
            name="rental_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
