# Generated by Django 4.2.30 on 2026-06-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0001_initial"),
        ("shoppingcart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcartitem",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shoppingcartitem",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Shop.shop",
            ),
        ),
        migrations.AddField(
            model_name="shoppingcartitem",
            name="transaction_type",
            field=models.CharField(
                choices=[("P", "Purchase"), ("R", "Rental")], default="P", max_length=1
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
