# Generated by Django 4.2.30 on 2026-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shoppingcart",
            "0002_shoppingcartitem_due_date_shoppingcartitem_shop_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="transaction_type",
            field=models.CharField(
                choices=[("P", "Kaufen"), ("R", "Ausleihen")], default="P", max_length=1
            ),
        ),
    ]
