# Generated by Django 4.2.30 on 2026-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingcart", "0003_alter_shoppingcartitem_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="transaction_type",
            field=models.CharField(
                choices=[("P", "Purchase"), ("R", "Rental")], default="P", max_length=1
            ),
        ),
    ]
