# Generated by Django 4.2.30 on 2026-06-25 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=2000)),
                (
                    "fsk",
                    models.IntegerField(
                        choices=[
                            (0, "FSK 0"),
                            (6, "FSK 6"),
                            (12, "FSK 12"),
                            (16, "FSK 16"),
                            (18, "FSK 18"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("C", "Comedy"),
                            ("A", "Action"),
                            ("R", "Romance"),
                            ("T", "Thriller"),
                            ("D", "Drama"),
                            ("H", "Horror"),
                        ],
                        max_length=2,
                    ),
                ),
                ("year", models.IntegerField()),
                ("director", models.TextField(max_length=100)),
                ("time", models.IntegerField()),
                ("actors", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500)),
                (
                    "stars",
                    models.IntegerField(
                        choices=[
                            (1, "1 Stern"),
                            (2, "2 Sterne"),
                            (3, "3 Sterne"),
                            (4, "4 Sterne"),
                            (5, "5 Sterne"),
                        ],
                        default=0,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Movie.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
                "ordering": ["-timestamp"],
                "unique_together": {("user", "movie")},
            },
        ),
        migrations.CreateModel(
            name="RatingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, max_length=300)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Movie.rating"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating Report",
                "verbose_name_plural": "Rating Reports",
                "unique_together": {("user", "rating")},
            },
        ),
        migrations.CreateModel(
            name="RatingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.IntegerField(choices=[(1, "Upvote"), (0, "Downvote")])),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Movie.rating"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating Feedback",
                "verbose_name_plural": "Rating Feedbacks",
                "unique_together": {("user", "rating")},
            },
        ),
    ]
