# Generated by Django 4.2.30 on 2026-06-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="details_pdf",
            field=models.FileField(blank=True, null=True, upload_to="movie_pdfs/"),
        ),
        migrations.AddField(
            model_name="movie",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
