# Generated by Django 4.2.30 on 2026-06-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movie", "0002_movie_details_pdf_movie_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("C", "Comedy"),
                    ("A", "Action"),
                    ("R", "Romance"),
                    ("D", "Drama"),
                    ("H", "Horror"),
                ],
                max_length=2,
            ),
        ),
    ]
