# Generated by Django 4.2.30 on 2026-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movie", "0003_alter_movie_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rental_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
