# Generated by Django 4.2.30 on 2026-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_movie_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreport',
            name='movie_pic',
            field=models.ImageField(blank=True, null=True, upload_to='movie_pics/'),
        ),
    ]
