# Generated by Django 4.2.30 on 2026-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_ratingreport_movie_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingreport',
            name='movie_pic',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_pic',
            field=models.ImageField(blank=True, null=True, upload_to='movie_pics/'),
        ),
    ]
