# Generated by Django 4.2.30 on 2026-07-07 19:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movie", "0007_rating_is_active_alter_rating_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rental_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="time",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.PositiveIntegerField(),
        ),
    ]
